version: '3'
services:
  nginx:
    build:
      context: ./_nginx
    image: iuga/nginx_site
    links:
        - node1:node1
    ports:
        - "80"
        - "443"
  node1:
    build:
      context: ./
    image: iuga/next_site
    ports:
        - "3000"